### ISSUE TITLE
No Suitable Driver Found Error in RegisterControlerTest 

### ISSUE THREAD

**Issue by azraoymaagac** [emirtarikarici/TMS#24]
java.sql.SQLException: No suitable driver found for jdbc:h2:mem:test;DB_CLOSE_DELAY=-1 error occurs when running the test. The way that database connection is handled should be changed @BeforeEach.

**Comment by emirtarikarici** [comment]
RegisterControlerTest/setUp() method is updated by the commit a91d793903226c64f2452f49cd8466fcec4df50d . After all, all the @BeforeEach methods are standardized.
